# This is a basic workflow to help you get started with Actions

name: Consulta CEP

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version
          
      # Runs a single command using the runners shell      
      - name: Step 2 Install Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra
        
      # Runs a set of commands using the runners shell
      - name: Step 3 Execute collection
        run: newman run ./viacep-ci.json -e ./viacep-env.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./results/Report.html
   
      # Runs a set of commands using the runners shell
      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
            name: report
            path: ./results/Report.html
